project/mysite/common/urls.py
from django.urls import path
# 사용자 인증에 관한 모듈
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

# 로그인 했을 때 어떤 화면을 띄울 것인지.
# 또한 아래 함수들을 이용해서 로그인에 관한 view를 만들지 않아도 된다.
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

project/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

# 이벤트는 url에 의해서 일어난다.
# index 대문 페이지

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
]

project/mysite/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_question_views, comment_answer_views

app_name = 'pybo'

urlpatterns = [
    # base
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('question/vote/delete/<int:question_id>/', question_views.question_vote_delete, name='question_vote_delete'),

    # commnet_question
    path('comment/create/question/<int:question_id>/', comment_question_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_question_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_question_views.comment_delete_question, name='comment_delete_question'),
    path('comment/question/vote/<int:comment_id>/', comment_question_views.comment_question_vote, name='comment_question_vote'),
    path('comment/question/vote/delete/<int:comment_id>/', comment_question_views.comment_question_vote_delete, name='comment_question_vote_delete'),

    # answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    path('answer/vote/delete/<int:answer_id>/', answer_views.answer_vote_delete, name='answer_vote_delete'),

    # comment_answer
    path('comment/create/answer/<int:answer_id>/', comment_answer_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_answer_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_answer_views.comment_delete_answer, name='comment_delete_answer'),
    path('comment/answer/vote/<int:comment_id>/', comment_answer_views.comment_answer_vote, name='comment_answer_vote'),
    path('comment/answer/vote/delete/<int:comment_id>/', comment_answer_views.comment_answer_vote_delete, name='comment_answer_vote_delete'),
]

project/mysite/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
from pybo.models import Question, Answer, Comment


def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')
    
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(answer__content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    # answer
    page = request.GET.get('page', '1')
    so = request.GET.get('so', 'recent')

    answer_list = Answer.objects.filter(question=question_id)
    if so == 'recommend':
        answer_list = answer_list.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        answer_list = answer_list.annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    else:
        answer_list = answer_list.order_by('-create_date')
    
    paginator = Paginator(answer_list, 5)
    page_obj = paginator.get_page(page)

    # comment
    page_cmt = request.GET.get('page_cmt', '1')
    so_cmt = request.GET.get('so_cmt', 'recent')

    comment_list = Comment.objects.filter(question=question_id)
    if so_cmt == 'recommend':
        comment_list = comment_list.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    else:
        comment_list = comment_list.order_by('-create_date')

    paginator_cmt = Paginator(comment_list, 5)
    page_cmt_obj = paginator_cmt.get_page(page_cmt)
    
    context = {'question': question, 'answer_list': page_obj, 'page': page, 'so': so, 'comment_list': page_cmt_obj, 'page_cmt': page_cmt, 'so_cmt': so_cmt}
    return render(request, 'pybo/question_detail.html', context)

project/mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

project/mysite/templates/form_errors.html
<!-- 회원가입에서 쓰일 수 있는 오류 추가 -->
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

project/mysite/templates/navbar.html
<!--부트스트랩이 제공하는 디자인을 그대로 사용했다-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>